# Generated by Django 5.2.7 on 2025-11-09 10:27

import django.forms.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(verbose_name=django.forms.widgets.PasswordInput)),
                ('location', models.CharField(choices=[('1', 'Toshkent'), ('2', "Farg'ona"), ('3', 'Andijon'), ('4', 'Namangan'), ('5', 'Samarqand'), ('6', 'Buxoro'), ('7', 'Xorazm'), ('8', 'Navoiy'), ('9', 'Jizzax'), ('10', 'Sirdaryo'), ('11', 'Qashqadaryo'), ('12', 'Surxondaryo')])),
                ('market_name', models.CharField(max_length=256)),
                ('product_category', models.CharField(choices=[('1', 'Meva-sabzavotlar'), ('2', 'Go‘sht va parranda mahsulotlari'), ('3', 'Sut va sut mahsulotlari'), ('4', 'Non va un mahsulotlari'), ('5', 'Ichimliklar'), ('6', 'Shakar va shirinliklar'), ('7', 'Oziq-ovqat ziravorlari'), ('8', 'Uy-ro‘zg‘or buyumlari'), ('9', 'Maishiy texnika'), ('10', 'Kiyim-kechak'), ('11', 'Go‘zallik va parvarish vositalari'), ('12', 'Qurilish mollari'), ('13', 'Avto ehtiyot qismlar'), ('14', 'Elektronika'), ('15', 'Hayvonlar uchun mahsulotlar')])),
            ],
        ),
    ]
