# Generated by Django 5.2.7 on 2025-11-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livebazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
